### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by lianghuatf** [qqwweee/keras-yolo3#32]
I meet a question for a long time,when I run python train.py, it will be as follows. 
![5](https://user-images.githubusercontent.com/33718751/39660021-c864b976-5068-11e8-99bf-23fd7f54ab97.png)

I try find this question,finally, I find this as follows
![3](https://user-images.githubusercontent.com/33718751/39659993-24008a7c-5068-11e8-9940-fa05f7114842.png)
it is amazing!, I write the 'model_body = yolo_body(image_input, num_anchors, num_classes)' twice,it will be ok. but I don't know why. can you help me?

**Comment by qqwweee** [comment]
skip_mismatch=True is required because the output layers is not with the same shape.
Each Keras layer has its name, like 'Conv1', 'Conv2', 'Conv3'... When you call yolo_body the first time, the model layers may be from 'Conv1' to 'Conv50'. And 'Conv51' to 'Conv100' the second time. Then load_weights does nothing for the reason that by_name=True and the origin weights model begins at 'Conv1'.
Try upgrade Keras if there is a key error on skip_mismatch.

**Comment by lianghuatf** [comment]
thank you,my keras is 2.1.2,I update the keras to 2.1.6 accordong to your suggestion,and solve this question .
thank you very much.
