### ISSUE TITLE
'FileNotFoundError: [Errno 2] No such file or directory: './coco2017/train2017/train2017/000000448521.jpg'

### ISSUE THREAD

**Issue by wyjko** [qqwweee/keras-yolo3#671]
When I use train.py with gpu ,it shows   'FileNotFoundError: [Errno 2] No such file or directory: './coco2017/train2017/train2017/000000448521.jpg''. I tried to use absolute path and relative path to generate train.txt,but it also shows the same error.Can you help me? Thank you very much!

**Comment by Kuuuo** [comment]
Have you solved the problem yet? I made a similar mistake

**Comment by wyjko** [comment]
> Have you solved the problem yet? I made a similar mistake

I use Google cloab，Then I found out that it was caused by the transmission problem between the hard disk and cloab. Only a few more connections were needed and no error was reported.

**Comment by Kuuuo** [comment]
OK,Thank you&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wyjko"<notifications@github.com&gt;; 
发送时间: 2020年7月20日(星期一) 晚上7:50
收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com&gt;; 
抄送: "Kuuuo"<36560912@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [qqwweee/keras-yolo3] &#39;FileNotFoundError: [Errno 2] No such file or directory: &#39;./coco2017/train2017/train2017/000000448521.jpg&#39; (#671)





  
Have you solved the problem yet? I made a similar mistake
  
I use Google cloab，Then I found out that it was caused by the transmission problem between the hard disk and cloab. Only a few more connections were needed and no error was reported.
