### ISSUE TITLE
How to train the model on our own dataset and classes? Can someone explain in somewhat more detail.

### ISSUE THREAD

**Issue by robsr** [qqwweee/keras-yolo3#74]

**Comment by robsr** [comment]
figured it out. thanks

**Comment by elcronos** [comment]
Could you please provide more information about it? I'm having the same problem

**Comment by someonelikeypp** [comment]
how to modify our own classes. whether just modify the coco_classes.txt. 

I got a UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((1, 1, 256, 21) vs (255, 256, 1, 1)).
although some people commented that The warning wouldn't matter.
but I want the correct answer.
